module.exports = [
    ['1', '1: Parx Casino to 54th-City'],
    ['2', '2: 20th-Johnston to Pulaski-Hunting Park'],
    ['3', '3: 33rd-Cecil B. Moore to Frankford Transportation Center'],
    ['4', '4: Fern Rock Transportation Center to Broad-Pattison'],
    ['5', '5: Front-Market to Frankford Transportation Center'],
    ['6', '6: Olney Transportation Center to Cheltenham-Ogontz'],
    ['7', '7: Pier 70 to 33rd-Dauphin'],
    ['8', '8: Olney Transportation Center to Frankford Transportation Center'],
    ['9', '9: 4th-Walnut to Andorra'],
    ['10', '10: 13th-Market to Malvern'],
    ['11', '11: 13th-Market to Darby Transportation Center'],
    ['12', '12: 3rd-Pine to 50th-Woodland'],
    ['13', '13: 13th-Market to Yeadon and Darby Transportation Center'],
    [
        '14',
        '14: Oxford Valley and Neshaminy Malls to Frankford Transportation Center',
    ],
    ['15', '15: 63rd-Girard to Richmond-Westmoreland '],
    ['16', '16: Cheltenham-Ogontz to City Hall'],
    ['17', '17: Front-Market to 20th-Johnston and Broad-Pattison'],
    ['18', '18: Fox Chase to Cedarbrook Plaza'],
    ['19', '19: Torresdale Station to Frankford Transportation Center'],
    ['20', '20: Philadelphia Mills to Frankford Transportation Center'],
    ['21', "21: Penn's Landing to 69th Street Transportation Center"],
    ['22', '22: Warminster and Willow Grove to Olney Transportation Center'],
    ['23', '23: Broad-Oregon to Chestnut Hill'],
    ['24', '24: Southampton & Rockledge to Frankford Transportation Center'],
    ['25', '25: Frankford Transportation Center to Columbus Commons'],
    ['26', '26: Frankford Transportation Center to Chelten Ave Station'],
    ['27', '27: Broad-Carpenter to Plymouth Meeting Mall'],
    ['28', '28: Fern Rock Transportation Center to Torresdale-Cottman'],
    ['29', '29: Pier 70 to 33rd-Dickinson'],
    [
        '30',
        '30: Amtrak 30th Street Station to 69th Street Transportation Center',
    ],
    ['31', '31: City Hall to 76th-City'],
    ['32', '32: Broad-Carpenter to Ridge-Lyceum'],
    ['33', "33: Penn's Landing to 23rd-Venango"],
    ['34', '34: 13th-Market to 61st-Baltimore'],
    ['35', '35: Manayunk - Roxborough Loop'],
    ['36', '36: 13th-Market to 80th-Eastwick'],
    ['37', '37: Chester Transportation Center to Broad-Snyder'],
    ['38', '38: 5th-Market to Wissahickon Transportation Center'],
    ['39', '39: Richmond-Cumberland to 33rd-Dauphin'],
    ['40', '40: 2nd-Lombard to Conshohocken-Monument'],
    ['42', "42: Penn's Landing to Wycombe"],
    ['43', '43: Richmond-Cumberland to 50th-Parkside'],
    ['44', '44: 5th-Market to Ardmore'],
    ['45', '45: Broad & Oregon to Noble & 12th'],
    ['46', '46: 58th-Baltimore to 63rd-Malvern'],
    ['47', '47: Whitman Plaza to 5th-Godfrey'],
    ['47m', '47m: Spring Garden via 9th Street'],
    ['48', '48: Front-Market to 27th-Allegheny'],
    [
        '50',
        '50: Parx Casino via Philadelphia Mills to Frankford Transportation Center',
    ],
    ['52', '52: 49th-Woodland to 54th-City or 50th-Parkside'],
    ['53', '53: Wayne-Carpenter to Broad-Hunting Park'],
    ['54', '54: Richmond-Cambria to 33rd-Dauphin'],
    ['55', '55: Doylestown and Willow Grove to Olney Transportation Center'],
    ['56', '56: 23rd-Venango or Bakers Centre to Torresdale-Cottman'],
    [
        '57',
        '57: Whitman Plaza to Rising Sun-Olney or Fern Rock Transportation Center',
    ],
    [
        '58',
        '58: Neshaminy Mall and Somerton to Frankford Transportation Center',
    ],
    ['59', '59: Castor-Bustleton to Arrott Transportation Center'],
    ['60', '60: 35th-Allegheny to Richmond-Westmoreland'],
    ['61', '61: 9th-Market to Manayunk'],
    ['62', '62: 9th-Market to Andorra'],
    ['64', '64: 50th-Parkside to Pier 70'],
    ['65', '65: Germantown-Chelten to 69th Street Transportation Center'],
    ['66', '66: Frankford Transportation Center to Frankford-Knights'],
    [
        '67',
        '67: Philadelphia Mills and Bustleton to Frankford Transportation Center',
    ],
    ['68', '68: Broad-Oregon to UPS or 69th Street Transportation Center'],
    [
        '70',
        '70: Frankford-Gregg and Torresdale-Cottman to Fern Rock Transportation Center',
    ],
    ['73', '73: Frankford Transportation Center to Richmond-Westmoreland'],
    ['75', '75: Wayne Junction to Arrott Transportation Center'],
    ['77', '77: Roosevelt-St. Vincent to Chestnut Hill'],
    ['78', '78: Express Cornwells Heights to Center City'],
    ['79', '79: Columbus Commons to 29th-Snyder'],
    ['80', '80: Express Horsham to Olney Transportation Center'],
    [
        '84',
        '84: Bustleton-County Line and Philadelphia Mills to Frankford Transportation Center',
    ],
    [
        '88',
        '88: Bethayres and Holme-Pennypack to Frankford Transportation Center',
    ],
    ['89', '89: Front-Dauphin to Arrott Transportation Center'],
    ['90', '90: Plymouth Meeting Mall to Norristown Transportation Center'],
    ['91', '91: Graterford to Norristown Transportation Center'],
    ['92', '92: Exton to King of Prussia'],
    ['93', '93: Pottstown to Norristown Transportation Center'],
    ['94', '94: Montgomery Mall to Chestnut Hill'],
    ['95', '95: Willow Grove to Gulph Mills'],
    ['96', '96: Lansdale to Norristown Transportation Center'],
    ['97', '97: Chestnut Hill to Norristown Transportation Center'],
    [
        '98',
        '98: Blue Bell or Plymouth Meeting Mall to Norristown Transportation Center',
    ],
    ['99', '99: Phoenixville to Norristown Transportation Center'],
    ['101', '101: Media to 69th Street Transportation Center'],
    ['102', '102: Sharon Hill to 69th Street Transportation Center'],
    ['103', '103: Ardmore to 69th Street Transportation Center'],
    [
        '104',
        '104: West Chester University to 69th Street Transportation Center',
    ],
    ['105', '105: Paoli to 69th Street Transportation Center'],
    ['106', '106: Ardmore and Paoli to 69th Street Transportation Center'],
    ['107', '107: Lawrence Park to 69th Street Transportation Center'],
    [
        '108',
        '108: Airport and Airport Business Center to 69th Street Transportation Center',
    ],
    [
        '109',
        '109: Chester Transportation Center to 69th Street Transportation Center',
    ],
    [
        '110',
        '110: Penn State and Springfield Mall to 69th Street Transportation Center',
    ],
    [
        '111',
        '111: Chadds Ford and Penn State to 69th Street Transportation Center',
    ],
    [
        '112',
        '112: Delaware County Community College to 69th Street Transportation Center',
    ],
    [
        '113',
        '113: Tri-State Mall and Darby Transportation Center to 69th Street Transportation Center',
    ],
    [
        '114',
        '114: Penn State and I-95 Industrial Park to Darby Transportation Center',
    ],
    ['115', '115: Delaware County Community College to Airport'],
    ['117', '117: Penn State to I-95 Industrial Park'],
    ['118', '118: Newtown Square to Chester Transportation Center'],
    ['119', '119: Cheyney University to Chester Transportation Center'],
    ['120', '120: Cheyney University to 69th Street Transportation Center'],
    ['123', '123: King of Prussia to 69th Street Transportation Center'],
    ['124', '124: Chesterbrook and King of Prussia to 13th-Market'],
    ['125', '125: Valley Forge and King of Prussia to 13th-Market'],
    ['126', '126: Lawrence Park to 69th Street Transportation Center'],
    ['127', '127: Trenton Transit Center to Oxford Valley Mall'],
    ['128', '128: Neshaminy Mall to Oxford Valley Mall'],
    ['129', '129: Frankford-Knights to Oxford Valley Mall'],
    ['130', '130: Bucks County Community College to Frankford-Knights'],
    ['131', '131: Audubon to Norristown Transportation Center'],
    ['132', '132: Telford to Montgomery Mall'],
    ['133', '133: Frankford-Knights to Bensalem'],
    ['139', '139: Limerick to King of Prussia'],
    ['150', '150: Parx Casino to Plymouth Meeting Mall'],
    ['201', '201: Fort Washington Office Center to Fort Washington Station'],
    ['204', '204: Eagleview to Paoli Station'],
    ['205', '205: Chesterbrook to Paoli Station'],
    ['206', '206: Paoli Station to the Commons at Great Valley'],
    ['310', '310: Horsham Breeze'],

    [
        'BSO',
        'BSO: NiteOwl Fern Rock Transportation Center to South Philadelphia',
    ],
    [
        'MFO',
        'MFO: NiteOwl Frankford Transportation Center to 69th Street Transportation Center',
    ],
    [
        'G',
        'G: Overbrook and Lankenau Med. Cntr. to Columbus Commons or Food Distribution Center',
    ],
    ['H', 'H: Broad-Erie to Cheltenham-Ogontz'],
    ['XH', 'XH: Broad-Erie to Cheltenham-Ogontz'],
    ['J', 'J: Chelten-Wissahickon to Richmond-Orthodox'],
    ['K', 'K: Ridge-Midvale to Arrott Transportation Center'],
    [
        'L',
        'L: Erdenheim or Plymouth Meeting Mall to Olney Transportation Center',
    ],
    [
        'R',
        'R: Henry-Midvale and Wissahickon Transportation Center to Frankford Transportation Center',
    ],
    ['LUCY', 'LUCY: Loop through University City'],

    ['L1', 'Subway: L - Market-Frankfort'],
    ['B1', 'Subway: B - Broad Street'],
    ['B3', 'Subway: B - Broad Street Express'],
    ['M1', 'Subway: Norristown High Speed Line'],

    ['T1', 'Trolley: Route 10'],
    ['T2', 'Trolley: Route 34'],
    ['T3', 'Trolley: Route 13'],
    ['T4', 'Trolley: Route 11'],
    ['T5', 'Trolley: Route 36'],
    ['G1', 'Trolley: G - Route 15'],
    ['D1', 'Trolley: Route 10'],
    ['D2', 'Trolley: Route 34'],
];
