module.exports = {
    L1: [
        // Market-Frankfort line
        '69th St Transportation Center - MFL EB',
        'Millbourne',
        '63rd St',
        '60th St',
        '56th St',
        '52nd St',
        '46th St',
        '40th St',
        '34th St',
        '30th St Station - MFL',
        '15th St Station - MFL',
        '13th St',
        '11th St',
        '8th St Station - MFL',
        '5th St/Independence Hall',
        '2nd St',
        'Spring Garden',
        'Girard Station - MFL',
        'Berks',
        'York-Dauphin',
        'Huntingdon',
        'Somerset',
        'Allegheny Station - MFL',
        'Tioga',
        'Erie-Torresdale',
        'Church',
        'Arrott Transportation Center - MFL',
        'Frankford Transportation Center - MFL',
    ],
    B1: [
        // Broad Street
        'Fern Rock Transportation Center - BSL',
        'Olney Transportation Center - BSL',
        'Logan',
        'Wyoming',
        'Hunting Park',
        'Erie',
        'Allegheny Station - BSL',
        'North Philadelphia',
        'Susquehanna-Dauphin',
        'Cecil B. Moore',
        'Girard Station - BSL',
        'Fairmount',
        'Spring Garden Station - BSL',
        'Race-Vine',
        'City Hall Station - BSL',
        'Walnut-Locust',
        'Lombard-South',
        'Ellsworth-Federal',
        'Tasker-Morris',
        'Snyder',
        'Oregon',
        'NRG Station',
    ],
    B3: [
        // Broad Street Express
        'Fern Rock Transportation Center - BSL',
        'Olney Transportation Center - BSL',
        'Erie',
        'North Philadelphia',
        'Girard Station - BSL',
        'Fairmount',
        'Chinatown',
        '8th St & Market St - BSL',
    ],
    // G1: [ // Route 15 trolley
    //     'Richmond St & Westmoreland St Loop',
    //     'Richmond St & Allegheny Av',
    //     'Richmond St & Clearfield St',
    //     'Richmond St & Ann St',
    //     'Richmond St & Cambria St',
    //     'Richmond St & Somerset St',
    //     'Richmond St & Lehigh Av',
    //     'Richmond St & Huntingdon St',
    //     'Richmond St & Cumberland St',
    //     'Richmond St & Girard Av',
    //     'Girard Av & Berks St',
    //     'Girard Av & Palmer St',
    //     'Girard Av & Columbia Av',
    //     'Frankford Av & Girard Av - FS',
    //     'Frankford Av & Richmond St',
    //     'Frankford Av & Delaware Av',
    //     'Frankford Av & Delaware Av Loop',
    //     'Frankford Av & Delaware Av - FS',
    //     'Frankford Av & Richmond St',
    //     'Frankford Av & Girard Av',
    //     'Girard Av & Front St',
    //     'Girard Av & 2nd St',
    //     'Girard Av & 3rd St',
    //     'Girard Av & 4th St',
    //     'Girard Av & 5th St',
    //     'Girard Av & 7th St',
    //     'Girard Av & 8th St',
    //     'Girard Av & 11th St',
    //     'Girard Av & 12th St',
    //     'Girard Av & Broad St',
    //     'Girard Av & 16th St',
    //     'Girard Av & 17th St',
    //     'Girard Av & Ridge Av',
    //     'Girard Av & 19th St',
    //     'Girard Av & 20th St',
    //     'Girard Av & Corinthian Av',
    //     'Girard Av & 24th St',
    //     'Poplar St & 25th St',
    //     'Girard Av & 26th St',
    //     'Girard Av & 27th St',
    //     'Girard Av & 28th St',
    //     'Girard Av & 29th St',
    //     'Girard Av & 31st St',
    //     'Girard Av & 33rd St',
    //     'Girard Av & 34th St - MBFS',
    //     'Girard Av & 39th St',
    //     'Girard Av & 40th St - FS',
    //     'Girard Av & 41st St',
    //     'Girard Av & 42nd St',
    //     'Girard Av & Belmont Av',
    //     'Girard Av & Merion Av',
    //     'Girard Av & 49th St',
    //     'Girard Av & 51st St',
    //     'Girard Av & 52nd St',
    //     'Girard Av & 54th St',
    //     'Girard Av & 56th St',
    //     'Girard Av & 57th St',
    //     'Girard Av & 59th St',
    //     'Girard Av & 60th St',
    //     'Haverford Av & 61st St',
    //     'Haverford Av & 62nd St',
    //     'Haverford Av & 63rd St',
    //     'Girard Av & 63rd St - MBFS',
    // ],
    // 101: [
    //     '69th St Transportation Center West Terminal',
    //     'Fairfield Av Station - FS',
    //     'Walnut St Station - FS',
    //     'Avon Rd Station - FS',
    //     'Hilltop Rd Station - FS',
    //     'Beverly Blvd Station - FS',
    //     'Congress Av Station - FS',
    //     'Lansdowne Av Station - FS',
    //     'Drexel Park Station',
    //     'Irvington Rd Station',
    //     'Drexel Hill Junction Station',
    //     'Huey Av Station - FS',
    //     'School Ln Station - FS',
    //     'Aronimink Station',
    //     'Anderson Av Station',
    //     'Drexelbrook Station',
    //     'Drexeline Station',
    //     'Scenic Rd Station',
    //     'Springfield Rd Station - FS',
    //     'Saxer Av Station',
    //     'Leamy Av Station',
    //     'Woodland Av Station',
    //     'Thomson Av Station - FS',
    //     'Springfield Mall Station',
    //     'Paper Mill Rd Station',
    //     '96 Signal - not a stop',
    //     'Pine Ridge Station - FS',
    //     'Beatty Rd Station',
    //     'Providence Rd Station',
    //     'Manchester Av Station',
    //     'Edgmont St Station',
    //     'Monroe St Station',
    //     'Jackson St Station',
    //     'Olive St Station',
    //     'Veterans Square Station',
    //     'Orange St Station - MBFS',
    // ],
    // 102: [
    //     '69th St Transportation Center West Terminal',
    //     'Fairfield Av Station - FS',
    //     'Walnut St Station - FS',
    //     'Avon Rd Station - FS',
    //     'Hilltop Rd Station - FS',
    //     'Beverly Blvd Station - FS',
    //     'Congress Av Station - FS',
    //     'Lansdowne Av Station - FS',
    //     'Drexel Park Station',
    //     'Irvington Rd Station',
    //     'Drexel Hill Junction Station',
    //     'Garrettford Station - FS',
    //     'Drexel Manor Station - MBFS',
    //     'Marshall Rd Station',
    //     'Creek Rd Station',
    //     'Baltimore Av Station',
    //     'Penn St Station',
    //     'Springfield Rd Station',
    //     'Clifton Aldan Station - FS',
    //     'Providence Rd Station',
    //     'Magnolia Av Station',
    //     'North St Station',
    //     'Bartram Av Station',
    //     'Andrews Av Station',
    //     'MacDade Blvd Station',
    //     'Sharon Hill Station',
    // ],
    M1: [
        // Norristown High Speed Line
        '69th St Transportation Center - NHSL',
        'Parkview Station - NHSL',
        'Township Line Rd Station - NHSL',
        'Penfield Station Manoa Rd - NHSL',
        'Beechwood Brookline Station - NHSL',
        'Wynnewood Rd Station - NHSL',
        'Ardmore Junction Station - NHSL',
        'Ardmore Av Station - NHSL',
        'Haverford Station - NHSL',
        'Bryn Mawr Station - NHSL',
        'Roberts Rd Station - NHSL',
        'Garrett Hill Station - NHSL',
        'Stadium Station - NHSL',
        'Villanova Station - NHSL',
        'Radnor Station - NHSL',
        'Matsonford Station - NHSL',
        'Gulph Mills Station - NHSL',
        'Hughes Park Station - NHSL',
        'DeKalb St Station - NHSL',
        'Bridgeport Station - NHSL',
        'Norristown Transportation Center - NHSL',
    ],
};
