export default [
    ['9th Street Station', '9th St'],
    ['30th Street Station', '30th Street Station'],
    ['49th Street', '49th St'],
    ['Airport Terminal A', 'Airport Terminal A'],
    ['Airport Terminal B', 'Airport Terminal B'],
    ['Airport Terminals C & D', 'Airport Terminal C-D'],
    ['Airport Terminals E & F', 'Airport Terminal E-F'],
    ['Allegheny', 'Allegheny'],
    ['Allen Lane', 'Allen Lane'],
    ['Ambler', 'Ambler'],
    ['Angora', 'Angora'],
    ['Ardmore', 'Ardmore'],
    ['Ardsley', 'Ardsley'],
    ['Bala', 'Bala'],
    ['Berwyn', 'Berwyn'],
    ['Bethayres', 'Bethayres'],
    ['Bridesburg', 'Bridesburg'],
    ['Bristol', 'Bristol'],
    ['Bryn Mawr', 'Bryn Mawr'],
    ['Carpenter', 'Carpenter'],
    ['Chalfont', 'Chalfont'],
    ['Chelten Avenue', 'Chelten Avenue'],
    ['Cheltenham', 'Cheltenham'],
    ['Chester Transportation Center', 'Chester TC'],
    ['Chestnut Hill East', 'Chestnut Hill East'],
    ['Chestnut Hill West', 'Chestnut Hill West'],
    ['Churchmans Crossing', 'Churchmans Crossing'],
    ['Claymont', 'Claymont'],
    ['Clifton-Aldan', 'Clifton-Aldan'],
    ['Colmar', 'Colmar'],
    ['Conshohocken', 'Conshohocken'],
    ['Cornwells Heights', 'Cornwells Heights'],
    ['Crestmont', 'Crestmont'],
    ['Croydon', 'Croydon'],
    ['Crum Lynne', 'Crum Lynne'],
    ['Curtis Park', 'Curtis Park'],
    ['Cynwyd', 'Cynwyd'],
    ['Station Name', 'Parameter'],
    ['Darby', 'Darby'],
    ['Daylesford', 'Daylesford'],
    ['Delaware Valley College', 'Delaware Valley College'],
    ['Devon', 'Devon'],
    ['Downingtown', 'Downingtown'],
    ['Doylestown', 'Doylestown'],
    ['East Falls', 'East Falls'],
    ['Eastwick Station', 'Eastwick Station'],
    ['Eddington', 'Eddington'],
    ['Eddystone', 'Eddystone'],
    ['Elkins Park', 'Elkins Park'],
    ['Elm Street, Norristown', 'Elm St'],
    ['Elwyn', 'Elwyn Station'],
    ['Exton', 'Exton'],
    ['Fern Rock Transportation Center', 'Fern Rock TC'],
    ['Fernwood-Yeadon', 'Fernwood'],
    ['Folcroft', 'Folcroft'],
    ['Forest Hills', 'Forest Hills'],
    ['Fort Washington', 'Ft Washington'],
    ['Fortuna', 'Fortuna'],
    ['Fox Chase', 'Fox Chase'],
    ['Germantown', 'Germantown'],
    ['Gladstone', 'Gladstone'],
    ['Glenolden', 'Glenolden'],
    ['Glenside', 'Glenside'],
    ['Gravers', 'Gravers'],
    ['Gwynedd Valley', 'Gwynedd Valley'],
    ['Station Name', 'Parameter'],
    ['Hatboro', 'Hatboro'],
    ['Haverford', 'Haverford'],
    ['Highland', 'Highland'],
    ['Highland Avenue', 'Highland Ave'],
    ['Holmesburg Junction', 'Holmesburg Jct'],
    ['Ivy Ridge', 'Ivy Ridge'],
    ['Jefferson Station (Market East)', 'Market East'],
    ['Jenkintown-Wyncote', 'Jenkintown-Wyncote'],
    ['Station Name', 'Parameter'],
    ['Langhorne', 'Langhorne'],
    ['Lansdale', 'Lansdale'],
    ['Lansdowne', 'Lansdowne'],
    ['Lawndale', 'Lawndale'],
    ['Levittown', 'Levittown'],
    ['Link Belt', 'Link Belt'],
    ['Main Street, Norristown', 'Main St'],
    ['Malvern', 'Malvern'],
    ['Manayunk', 'Manayunk'],
    ['Marcus Hook', 'Marcus Hook'],
    ['Meadowbrook', 'Meadowbrook'],
    ['Media', 'Media'],
    ['Melrose Park', 'Melrose Park'],
    ['Merion', 'Merion'],
    ['Miquon', 'Miquon'],
    ['Morton', 'Morton'],
    ['Mount Airy', 'Mt Airy'],
    ['Moylan-Rose Valley', 'Moylan-Rose Valley'],
    ['Narberth', 'Narberth'],
    ['Neshaminy Falls', 'Neshaminy Falls'],
    ['New Britain', 'New Britain'],
    ['Newark', 'Newark'],
    ['Noble', 'Noble'],
    ['Norristown Transportation Center', 'Norristown TC'],
    ['North Broad', 'North Broad St'],
    ['North Hills', 'North Hills'],
    ['North Philadelphia', 'North Philadelphia'],
    ['North Wales', 'North Wales'],
    ['Norwood', 'Norwood'],
    ['Olney', 'Olney'],
    ['Oreland', 'Oreland'],
    ['Overbrook', 'Overbrook'],
    ['Station Name', 'Parameter'],
    ['Paoli', 'Paoli'],
    ['Penllyn', 'Penllyn'],
    ['Pennbrook', 'Pennbrook'],
    ['Penn Medicine Station (University City)', 'Penn Medicine Station'],
    ['Philmont', 'Philmont'],
    ['Primos', 'Primos'],
    ['Prospect Park', 'Prospect Park'],
    ['Queen Lane', 'Queen Lane'],
    ['Radnor', 'Radnor'],
    ['Ridley Park', 'Ridley Park'],
    ['Rosemont', 'Rosemont'],
    ['Roslyn', 'Roslyn'],
    ['Rydal', 'Rydal'],
    ['Ryers', 'Ryers'],
    ['Secane', 'Secane'],
    ['Sedgwick', 'Sedgwick'],
    ['Sharon Hill', 'Sharon Hill'],
    ['Somerton', 'Somerton'],
    ['Spring Mill', 'Spring Mill'],
    ['St. Davids', 'St. Davids'],
    ['St. Martins', 'St. Martins'],
    ['Stenton', 'Stenton'],
    ['Strafford', 'Strafford'],
    ['Suburban Station', 'Suburban Station'],
    ['Swarthmore', 'Swarthmore'],
    ['Station Name', 'Parameter'],
    ['Tacony', 'Tacony'],
    ['Temple University', 'Temple U'],
    ['Thorndale', 'Thorndale'],
    ['Torresdale', 'Torresdale'],
    ['Trenton Transit Center', 'Trenton'],
    ['Trevose', 'Trevose'],
    ['Tulpehocken', 'Tulpehocken'],
    ['Upsal', 'Upsal'],
    ['Villanova', 'Villanova'],
    ['Wallingford', 'Wallingford'],
    ['Warminster', 'Warminster'],
    ['Washington Lane', 'Washington Lane'],
    ['Wayne', 'Wayne'],
    ['Wayne Junction', 'Wayne Jct'],
    ['West Trenton', 'West Trenton'],
    ['Whitford', 'Whitford'],
    ['Willow Grove', 'Willow Grove'],
    ['Wilmington', 'Wilmington'],
    ['Wissahickon', 'Wissahickon'],
    ['Wister', 'Wister'],
    ['Woodbourne', 'Woodbourne'],
    ['Wyndmoor', 'Wyndmoor'],
    ['Wynnefield Avenue', 'Wynnefield Avenue'],
    ['Wynnewood', 'Wynnewood'],
    ['Station Name', 'Parameter'],
    ['Yardley', 'Yardley'],
];
